### ISSUE TITLE
유저 데이터 수정 기능 구현

### ISSUE THREAD

**Issue by kanghyun98** [gdsc-ssu/sasil-server#50]
## Epic
https://github.com/gdsc-ssu/sasil-front/issues/76

## Description
프로필 사진과 닉네임 변경 기능 구현

## TODO
- [x] 프로필 사진 수정
- [x] 닉네임 변경
- [x] swagger 추가

**Comment by gomjellie** [comment]
gdsc는 끝나도 플젝은 계속되는군요 ㄷㄷ
